# import scrapy

# class BlogSpider(scrapy.Spider):
#     name = "blogspider"
#     start_urls = ['https://www.creativebloq.com/how-to/draw-a-dog',
#                   'https://www.creativebloq.com/how-to/draw-a-cat',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-horse/2#01-how-to-draw-a-horse-body',
#                  'https://www.creativebloq.com/how-to/draw-a-wolf',
#                  'https://www.creativebloq.com/how-to/draw-a-bird',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-lion',
#                  'https://www.creativebloq.com/how-to/draw-an-elephant',
#                  'https://www.creativebloq.com/character-design/how-draw-bear-21619079',
#                  'https://www.creativebloq.com/digital-art/master-art-painting-fur-31514473',
#                  'https://www.creativebloq.com/features/15-tips-for-creating-characterful-creature-art',
#                  'https://www.creativebloq.com/how-to/how-to-begin-a-figure-drawing',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-nose',
#                  'https://www.creativebloq.com/art/how-draw-hands-51620226',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-rose',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-landscape-with-pastels']
    
#     def parse(self, response):
#         t = ''
#         SET_SELECTOR = '.content-wrapper'
#         SET_S = '.breadcrumb'
#         for brickset in response.css(SET_S):

#             NAME_SELECTOR = 'li ::text'
#             text = brickset.css(NAME_SELECTOR).extract()
#             c = ''.join(text)
#             t = t+c+'\n'
#             yield {
#                 'name': brickset.css(NAME_SELECTOR).extract()
#             }
#         for brickset in response.css(SET_SELECTOR):

#             NAME_SELECTOR = 'p ::text'
#             text = brickset.css(NAME_SELECTOR).extract()
#             c = ''.join(text)
#             t = t+c+'\n'
#             yield {
#                 'name': brickset.css(NAME_SELECTOR).extract()
#             }
# import scrapy

# class BlogSpider(scrapy.Spider):
#     name = "blogspider"
#     start_urls = ['https://www.creativebloq.com/how-to/draw-a-dog',
#                   'https://www.creativebloq.com/how-to/draw-a-cat',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-horse/2#01-how-to-draw-a-horse-body',
#                  'https://www.creativebloq.com/how-to/draw-a-wolf',
#                  'https://www.creativebloq.com/how-to/draw-a-bird',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-lion',
#                  'https://www.creativebloq.com/how-to/draw-an-elephant',
#                  'https://www.creativebloq.com/character-design/how-draw-bear-21619079',
#                  'https://www.creativebloq.com/digital-art/master-art-painting-fur-31514473',
#                  'https://www.creativebloq.com/features/15-tips-for-creating-characterful-creature-art',
#                  'https://www.creativebloq.com/how-to/how-to-begin-a-figure-drawing',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-nose',
#                  'https://www.creativebloq.com/art/how-draw-hands-51620226',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-rose',
#                  'https://www.creativebloq.com/how-to/how-to-draw-a-landscape-with-pastels']
    
#     def parse(self, response):
#         t = ''
#         SET_SELECTOR = '.content-wrapper'
#         SET_S = '.breadcrumb'
#         for brickset in response.css(SET_S):

#             NAME_SELECTOR = 'li ::text'
#             text = brickset.css(NAME_SELECTOR).extract()
#             c = ''.join(text)
#             t = t+c+'\n'
#             yield {
#                 'name': brickset.css(NAME_SELECTOR).extract()
#             }
#         for brickset in response.css(SET_SELECTOR):

#             NAME_SELECTOR = 'p ::text'
#             text = brickset.css(NAME_SELECTOR).extract()
#             c = ''.join(text)
#             t = t+c+'\n'
#             yield {
#                 'name': brickset.css(NAME_SELECTOR).extract()
#             }
#         with open("Output.txt", "a+") as text_file:
#             text_file.write(t)
            
import scrapy

class BlogSpider(scrapy.Spider):
  name = "blogspider"
  start_urls = ['https://easydrawingguides.com/how-to-draw-a-bat/',
    'https://easydrawingguides.com/how-to-draw-a-bear/',
    'https://easydrawingguides.com/how-to-draw-a-beaver/',
    'https://easydrawingguides.com/how-to-draw-a-black-cat/',
    'https://easydrawingguides.com/how-to-draw-a-buffalo/',
    'https://easydrawingguides.com/how-to-draw-a-bunny-in-cartoon-style/',
    'https://easydrawingguides.com/how-to-draw-a-bunny-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-camel/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-cow/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-goat/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-kangaroo/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-pig/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-reindeer/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-squirrel/',
    'https://easydrawingguides.com/how-to-draw-a-cat-face/',
    'https://easydrawingguides.com/how-to-draw-a-cheetah/',
    'https://easydrawingguides.com/how-to-draw-a-cute-narwhal/',
    'https://easydrawingguides.com/how-to-draw-a-deer/',
    'https://easydrawingguides.com/how-to-draw-a-donkey/',
    'https://easydrawingguides.com/how-to-draw-a-fox/',
    'https://easydrawingguides.com/how-to-draw-a-giraffe/',
    'https://easydrawingguides.com/how-to-draw-a-guinea-pig/',
    'https://easydrawingguides.com/how-to-draw-a-hippo/',
    'https://easydrawingguides.com/how-to-draw-a-husky/',
    'https://easydrawingguides.com/how-to-draw-a-kitten/',
    'https://easydrawingguides.com/how-to-draw-a-koala/',
    'https://easydrawingguides.com/how-to-draw-a-lion/',
    'https://easydrawingguides.com/how-to-draw-a-monkey-in-cartoon-style/',
    'https://easydrawingguides.com/how-to-draw-a-moose/',
    'https://easydrawingguides.com/how-to-draw-a-mouse/',
    'https://easydrawingguides.com/how-to-draw-a-polar-bear-cub/',
    'https://easydrawingguides.com/how-to-draw-a-pug/',
    'https://easydrawingguides.com/how-to-draw-a-raccoon/',
    'https://easydrawingguides.com/how-to-draw-a-rat/',
    'https://easydrawingguides.com/how-to-draw-a-red-panda/',
    'https://easydrawingguides.com/how-to-draw-a-sheep-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-sloth/',
    'https://easydrawingguides.com/how-to-draw-a-unicorn/',
    'https://easydrawingguides.com/how-to-draw-a-whale/',
    'https://easydrawingguides.com/how-to-draw-a-wolf/',
    'https://easydrawingguides.com/how-to-draw-a-zebra-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-an-arctic-fox/',
    'https://easydrawingguides.com/how-to-draw-an-easter-bunny/',
    'https://easydrawingguides.com/how-to-draw-an-elephant/',
    'https://easydrawingguides.com/how-to-draw-an-orca/',
    'https://easydrawingguides.com/how-to-draw-an-otter/',
    'https://easydrawingguides.com/how-to-draw-lion-head/',
    'https://easydrawingguides.com/how-to-draw-a-banana/',
    'https://easydrawingguides.com/how-to-draw-a-bush/',
    'https://easydrawingguides.com/how-to-draw-a-butterfly-garden/',
    'https://easydrawingguides.com/how-to-draw-a-calla-lily/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-forest/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-tree/',
    'https://easydrawingguides.com/how-to-draw-a-daffodil/',
    'https://easydrawingguides.com/how-to-draw-a-daisy-flower/',
    'https://easydrawingguides.com/how-to-draw-a-dandelion/',
    'https://easydrawingguides.com/how-to-draw-a-fall-scenery/',
    'https://easydrawingguides.com/how-to-draw-a-flower-bouquet/',
    'https://easydrawingguides.com/how-to-draw-a-flower-garden/',
    'https://easydrawingguides.com/how-to-draw-a-hibiscus/',
    'https://easydrawingguides.com/how-to-draw-a-jack-o-lantern/',
    'https://easydrawingguides.com/how-to-draw-a-leaf/',
    'https://easydrawingguides.com/how-to-draw-a-lemon/',
    'https://easydrawingguides.com/how-to-draw-a-lily-of-the-valley/',
    'https://easydrawingguides.com/how-to-draw-a-lily/',
    'https://easydrawingguides.com/how-to-draw-a-mothers-day-flower/',
    'https://easydrawingguides.com/how-to-draw-a-mushroom/',
    'https://easydrawingguides.com/how-to-draw-a-palm-tree/',
    'https://easydrawingguides.com/how-to-draw-a-peony/',
    'https://easydrawingguides.com/how-to-draw-a-pineapple/',
    'https://easydrawingguides.com/how-to-draw-a-pinecone/',
    'https://easydrawingguides.com/how-to-draw-a-poinsettia/',
    'https://easydrawingguides.com/how-to-draw-a-poppy/',
    'https://easydrawingguides.com/how-to-draw-a-pumpkin/',
    'https://easydrawingguides.com/how-to-draw-a-rose-flower/',
    'https://easydrawingguides.com/how-to-draw-a-rose-with-stem/',
    'https://easydrawingguides.com/how-to-draw-a-simple-rose/',
    'https://easydrawingguides.com/how-to-draw-a-spruce/',
    'https://easydrawingguides.com/how-to-draw-a-strawberry/',
    'https://easydrawingguides.com/how-to-draw-a-sunflower-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-sunflower/',
    'https://easydrawingguides.com/how-to-draw-a-tomato/',
    'https://easydrawingguides.com/how-to-draw-a-tulip-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-watermelon-slice/',
    'https://easydrawingguides.com/how-to-draw-acorns/',
    'https://easydrawingguides.com/how-to-draw-an-apple/',
    'https://easydrawingguides.com/how-to-draw-an-easter-egg-tree/',
    'https://easydrawingguides.com/how-to-draw-an-orchid/',
    'https://easydrawingguides.com/how-to-draw-cartoon-flowers/',
    'https://easydrawingguides.com/how-to-draw-corn-cob/',
    'https://easydrawingguides.com/how-to-draw-dogwood-flowers/',
    'https://easydrawingguides.com/how-to-draw-fall-tree/',
    'https://easydrawingguides.com/how-to-draw-falling-leaves/',
    'https://easydrawingguides.com/how-to-draw-flowers-and-trees/',
    'https://easydrawingguides.com/how-to-draw-magnolia-flowers/',
    'https://easydrawingguides.com/how-to-draw-pears/',
    'https://easydrawingguides.com/how-to-draw-a-backpack/',
    'https://easydrawingguides.com/how-to-draw-a-baseball-bat/',
    'https://easydrawingguides.com/how-to-draw-a-baseball-cap/',
    'https://easydrawingguides.com/how-to-draw-a-baseball/',
    'https://easydrawingguides.com/how-to-draw-a-basketball-hoop/',
    'https://easydrawingguides.com/how-to-draw-a-basketball/',
    'https://easydrawingguides.com/how-to-draw-a-beginner-mandala-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-bike-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-boat/',
    'https://easydrawingguides.com/how-to-draw-a-book-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-burger/',
    'https://easydrawingguides.com/how-to-draw-a-burrito/',
    'https://easydrawingguides.com/how-to-draw-a-cake/',
    'https://easydrawingguides.com/how-to-draw-a-camera/',
    'https://easydrawingguides.com/how-to-draw-a-candle/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-car/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-castle/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-house/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-revolver/',
    'https://easydrawingguides.com/how-to-draw-a-chain/',
    'https://easydrawingguides.com/how-to-draw-a-cheese/',
    'https://easydrawingguides.com/how-to-draw-a-chef-hat/',
    'https://easydrawingguides.com/how-to-draw-a-christmas-stocking/',
    'https://easydrawingguides.com/how-to-draw-a-coffee-cup/',
    'https://easydrawingguides.com/how-to-draw-a-coffin/',
    'https://easydrawingguides.com/how-to-draw-a-compass/',
    'https://easydrawingguides.com/how-to-draw-a-crown/',
    'https://easydrawingguides.com/how-to-draw-a-cute-pencil/',
    'https://easydrawingguides.com/how-to-draw-a-cute-popsicle/',
    'https://easydrawingguides.com/how-to-draw-a-dads-trophy/',
    'https://easydrawingguides.com/how-to-draw-a-diamond-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-diamond-ring/',
    'https://easydrawingguides.com/how-to-draw-a-dollar-bill/',
    'https://easydrawingguides.com/how-to-draw-a-donut/',
    'https://easydrawingguides.com/how-to-draw-a-dress/',
    'https://easydrawingguides.com/how-to-draw-a-football-helmet/',
    'https://easydrawingguides.com/how-to-draw-a-football/',
    'https://easydrawingguides.com/how-to-draw-a-funny-taco/',
    'https://easydrawingguides.com/how-to-draw-a-gingerbread-house/',
    'https://easydrawingguides.com/how-to-draw-a-golf-club-bag/',
    'https://easydrawingguides.com/how-to-draw-a-guitar/',
    'https://easydrawingguides.com/how-to-draw-a-hammer-and-saw/',
    'https://easydrawingguides.com/how-to-draw-a-haunted-house/',
    'https://easydrawingguides.com/how-to-draw-a-hoodie/',
    'https://easydrawingguides.com/how-to-draw-a-hot-dog/',
    'https://easydrawingguides.com/how-to-draw-a-jacket/',
    'https://easydrawingguides.com/how-to-draw-a-jet/',
    'https://easydrawingguides.com/how-to-draw-a-kite/',
    'https://easydrawingguides.com/how-to-draw-a-lantern/',
    'https://easydrawingguides.com/how-to-draw-a-lighthouse/',
    'https://easydrawingguides.com/how-to-draw-a-mardi-gras-mask/',
    'https://easydrawingguides.com/how-to-draw-a-menorah/',
    'https://easydrawingguides.com/how-to-draw-a-microphone/',
    'https://easydrawingguides.com/how-to-draw-a-milk-carton/',
    'https://easydrawingguides.com/how-to-draw-a-monster-truck/',
    'https://easydrawingguides.com/how-to-draw-a-necklace/',
    'https://easydrawingguides.com/how-to-draw-a-nutcracker/',
    'https://easydrawingguides.com/how-to-draw-a-pinata/',
    'https://easydrawingguides.com/how-to-draw-a-pirate-ship/',
    'https://easydrawingguides.com/how-to-draw-a-pizza/',
    'https://easydrawingguides.com/how-to-draw-a-plane/',
    'https://easydrawingguides.com/how-to-draw-a-playground/',
    'https://easydrawingguides.com/how-to-draw-a-pot-of-gold/',
    'https://easydrawingguides.com/how-to-draw-a-robot/',
    'https://easydrawingguides.com/how-to-draw-a-sandwich/',
    'https://easydrawingguides.com/how-to-draw-a-scarf/',
    'https://easydrawingguides.com/how-to-draw-a-school/',
    'https://easydrawingguides.com/how-to-draw-a-scooter/',
    'https://easydrawingguides.com/how-to-draw-a-scroll/',
    'https://easydrawingguides.com/how-to-draw-a-ship-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-shirt/',
    'https://easydrawingguides.com/how-to-draw-a-skirt/',
    'https://easydrawingguides.com/how-to-draw-a-snowman/',
    'https://easydrawingguides.com/how-to-draw-a-soda-can/',
    'https://easydrawingguides.com/how-to-draw-a-stack-of-money/',
    'https://easydrawingguides.com/how-to-draw-a-sugar-skull/',
    'https://easydrawingguides.com/how-to-draw-a-sweater/',
    'https://easydrawingguides.com/how-to-draw-a-sword/',
    'https://easydrawingguides.com/how-to-draw-a-teddy-bear/',
    'https://easydrawingguides.com/how-to-draw-a-tombstone/',
    'https://easydrawingguides.com/how-to-draw-a-top-hat/',
    'https://easydrawingguides.com/how-to-draw-a-tractor/',
    'https://easydrawingguides.com/how-to-draw-a-train/',
    'https://easydrawingguides.com/how-to-draw-a-truck-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-ufo/',
    'https://easydrawingguides.com/how-to-draw-a-valentine-bear/',
    'https://easydrawingguides.com/how-to-draw-a-violin/',
    'https://easydrawingguides.com/how-to-draw-a-watering-can/',
    'https://easydrawingguides.com/how-to-draw-an-alarm-clock/',
    'https://easydrawingguides.com/how-to-draw-an-anchor/',
    'https://easydrawingguides.com/how-to-draw-an-arrow/',
    'https://easydrawingguides.com/how-to-draw-an-easter-basket/',
    'https://easydrawingguides.com/how-to-draw-an-hourglass/',
    'https://easydrawingguides.com/how-to-draw-an-i-love-you-heart/',
    'https://easydrawingguides.com/how-to-draw-an-igloo/',
    'https://easydrawingguides.com/how-to-draw-bacon-and-eggs/',
    'https://easydrawingguides.com/how-to-draw-candy-cane/',
    'https://easydrawingguides.com/how-to-draw-candy/',
    'https://easydrawingguides.com/how-to-draw-cartoon-money/',
    'https://easydrawingguides.com/how-to-draw-christmas-lights/',
    'https://easydrawingguides.com/how-to-draw-christmas-ornaments/',
    'https://easydrawingguides.com/how-to-draw-christmas-present/',
    'https://easydrawingguides.com/how-to-draw-christmas-wreath/',
    'https://easydrawingguides.com/how-to-draw-cinco-de-mayo/',
    'https://easydrawingguides.com/how-to-draw-cookies/',
    'https://easydrawingguides.com/how-to-draw-cowboy-hat/',
    'https://easydrawingguides.com/how-to-draw-dogwood-flowers/',
    'https://easydrawingguides.com/how-to-draw-draw-school-bus/',
    'https://easydrawingguides.com/how-to-draw-easter-eggs/',
    'https://easydrawingguides.com/how-to-draw-fireworks/',
    'https://easydrawingguides.com/how-to-draw-french-fries/',
    'https://easydrawingguides.com/how-to-draw-frosty-the-snowman/',
    'https://easydrawingguides.com/how-to-draw-gas-mask/',
    'https://easydrawingguides.com/how-to-draw-gems/',
    'https://easydrawingguides.com/how-to-draw-gingerbread-man/',
    'https://easydrawingguides.com/how-to-draw-gold/',
    'https://easydrawingguides.com/how-to-draw-graduation-cap/',
    'https://easydrawingguides.com/how-to-draw-handcuffs/',
    'https://easydrawingguides.com/how-to-draw-happy-new-year-2018/',
    'https://easydrawingguides.com/how-to-draw-hockey-sticks/',
    'https://easydrawingguides.com/how-to-draw-hot-air-balloon/',
    'https://easydrawingguides.com/how-to-draw-hot-chocolate/',
    'https://easydrawingguides.com/how-to-draw-ice-cream/',
    'https://easydrawingguides.com/how-to-draw-jeans/',
    'https://easydrawingguides.com/how-to-draw-lemonade/',
    'https://easydrawingguides.com/how-to-draw-man-made-things/',
    'https://easydrawingguides.com/how-to-draw-mittens/',
    'https://easydrawingguides.com/how-to-draw-mothers-day-heart/',
    'https://easydrawingguides.com/how-to-draw-pancakes/',
    'https://easydrawingguides.com/how-to-draw-pie/',
    'https://easydrawingguides.com/how-to-draw-pocket-watch/',
    'https://easydrawingguides.com/how-to-draw-popcorn/',
    'https://easydrawingguides.com/how-to-draw-salad/',
    'https://easydrawingguides.com/how-to-draw-santas-sleigh/',
    'https://easydrawingguides.com/how-to-draw-scarecrow/',
    'https://easydrawingguides.com/how-to-draw-school-books/',
    'https://easydrawingguides.com/how-to-draw-spaghetti/',
    'https://easydrawingguides.com/how-to-draw-sushi/',
    'https://easydrawingguides.com/how-to-draw-the-american-flag/',
    'https://easydrawingguides.com/how-to-draw-the-elf-on-the-shelf/',
    'https://easydrawingguides.com/how-to-draw-the-statue-of-liberty/',
    'https://easydrawingguides.com/how-to-draw-the-tardis/',
    'https://easydrawingguides.com/how-to-draw-a-baby/',
    'https://easydrawingguides.com/how-to-draw-a-baseball-player/',
    'https://easydrawingguides.com/how-to-draw-a-basketball-player/',
    'https://easydrawingguides.com/how-to-draw-a-boy/',
    'https://easydrawingguides.com/how-to-draw-a-braid/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-ninja/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-princess/',
    'https://easydrawingguides.com/how-to-draw-a-demon/',
    'https://easydrawingguides.com/how-to-draw-a-face-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-fairy/',
    'https://easydrawingguides.com/how-to-draw-a-fist/',
    'https://easydrawingguides.com/how-to-draw-a-football-player/',
    'https://easydrawingguides.com/how-to-draw-a-hand-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-hockey-player/',
    'https://easydrawingguides.com/how-to-draw-a-human-heart/',
    'https://easydrawingguides.com/how-to-draw-a-knight/',
    'https://easydrawingguides.com/how-to-draw-a-leprechaun/',
    'https://easydrawingguides.com/how-to-draw-a-mother-hugging-a-daughter/',
    'https://easydrawingguides.com/how-to-draw-a-mouth-and-tongue/',
    'https://easydrawingguides.com/how-to-draw-a-mummy/',
    'https://easydrawingguides.com/how-to-draw-a-nose-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-sad-girl-crying/',
    'https://easydrawingguides.com/how-to-draw-a-samurai/',
    'https://easydrawingguides.com/how-to-draw-a-teacher/',
    'https://easydrawingguides.com/how-to-draw-a-witch-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-zombie/',
    'https://easydrawingguides.com/how-to-draw-alien/',
    'https://easydrawingguides.com/how-to-draw-an-angel/',
    'https://easydrawingguides.com/how-to-draw-an-astronaut/',
    'https://easydrawingguides.com/how-to-draw-an-ear-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-an-elf/',
    'https://easydrawingguides.com/how-to-draw-an-eyeball/',
    'https://easydrawingguides.com/how-to-draw-anime-eyes/',
    'https://easydrawingguides.com/how-to-draw-anime-girl-face/',
    'https://easydrawingguides.com/how-to-draw-buddha/',
    'https://easydrawingguides.com/how-to-draw-captain-america/',
    'https://easydrawingguides.com/how-to-draw-cartoon-hair-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-cupid/',
    'https://easydrawingguides.com/how-to-draw-curly-hair-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-dreadlocks-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-eyes-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-feet-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-ghost-rider/',
    'https://easydrawingguides.com/how-to-draw-grim-reaper/',
    'https://easydrawingguides.com/how-to-draw-harry-potter/',
    'https://easydrawingguides.com/how-to-draw-holding-hands/',
    'https://easydrawingguides.com/how-to-draw-lips-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-manga-hair-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-people/',
    'https://easydrawingguides.com/how-to-draw-praying-hands/',
    'https://easydrawingguides.com/how-to-draw-santa-claus/',
    'https://easydrawingguides.com/how-to-draw-scary-clown/',
    'https://easydrawingguides.com/how-to-draw-tears-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-vampire/',
    'https://easydrawingguides.com/how-to-draw-werewolf/',
    'https://easydrawingguides.com/how-to-draw-3d-stairs/',
    'https://easydrawingguides.com/how-to-draw-a-3d-hole/',
    'https://easydrawingguides.com/how-to-draw-a-beach-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-brain-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-broken-heart-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-monster/',
    'https://easydrawingguides.com/how-to-draw-a-cartoon-sun/',
    'https://easydrawingguides.com/how-to-draw-a-crying-emoji/',
    'https://easydrawingguides.com/how-to-draw-a-fire/',
    'https://easydrawingguides.com/how-to-draw-a-galaxy/',
    'https://easydrawingguides.com/how-to-draw-a-ghost/',
    'https://easydrawingguides.com/how-to-draw-a-heart/',
    'https://easydrawingguides.com/how-to-draw-a-kiss-emoji/',
    'https://easydrawingguides.com/how-to-draw-a-night-sky-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-river-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-shoe-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-shooting-star/',
    'https://easydrawingguides.com/how-to-draw-a-skeleton/',
    'https://easydrawingguides.com/how-to-draw-a-skull/',
    'https://easydrawingguides.com/how-to-draw-a-slime/',
    'https://easydrawingguides.com/how-to-draw-a-snowflake-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-star/',
    'https://easydrawingguides.com/how-to-draw-a-tongue-out-emoji/',
    'https://easydrawingguides.com/how-to-draw-a-volcano-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-waterfall-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-a-wink-emoji/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-cube/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-heart/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-hexagon/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-square/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-star/',
    'https://easydrawingguides.com/how-to-draw-an-impossible-trident/',
    'https://easydrawingguides.com/how-to-draw-an-island-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-an-ocean-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-angel-wings/',
    'https://easydrawingguides.com/how-to-draw-boots-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-buddha/',
    'https://easydrawingguides.com/how-to-draw-cinco-de-mayo/',
    'https://easydrawingguides.com/how-to-draw-clouds-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-crying-laughing-emoji/',
    'https://easydrawingguides.com/how-to-draw-crystals-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-cupcake-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-emojis-happy-emoji/',
    'https://easydrawingguides.com/how-to-draw-flames-and-smoke-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-flaming-skull/',
    'https://easydrawingguides.com/how-to-draw-grass-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-impossible-stairs/',
    'https://easydrawingguides.com/how-to-draw-lightning-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-mountains-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-other-things/',
    'https://easydrawingguides.com/how-to-draw-rain-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-rocks-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-santa-claus/',
    'https://easydrawingguides.com/how-to-draw-the-impossible-triangle/',
    'https://easydrawingguides.com/how-to-draw-the-moon-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-the-sun-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-umbrella-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-waves-really-easy-drawing-tutorial/',
    'https://easydrawingguides.com/how-to-draw-winter-scenery/']

  def parse(self, response):
      t = ''
      SET_SELECTOR = '.guide-step-text'
      SET_S = '.guide-h2'
      for brickset in response.css(SET_S):

          NAME_SELECTOR = 'h2 ::text'
          text = brickset.css(NAME_SELECTOR).extract()
          c = ''.join(text)
          t = t+c+'\n'
          yield {
              'name': brickset.css(NAME_SELECTOR).extract()
          }
      for brickset in response.css(SET_SELECTOR):

          NAME_SELECTOR = 'p ::text' 
          text = brickset.css(NAME_SELECTOR).extract()
          c = ''.join(text)
          t = t+c+'\n'
          yield {
              'name': brickset.css(NAME_SELECTOR).extract()
          }
      with open("Output2.txt", "a+") as text_file:
          text_file.write(t) 